spring:
  application:
    name: security
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/project

server:
  port: 8080

jwt:
  secret:
    key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration: 86400000
